### ISSUE TITLE
How to deploy django-q with docker? 

### ISSUE THREAD

**Issue by Ondrados** [Koed00/django-q#513]
Assume this simple docker-compose file
```
version: "3.9"
   
services:  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
```

How can i add django-q process to handle all requests from `web` container? I could probably build same image with different command such as ` python manage.py qcluster` but I dont think this solution si elegant. Could you suggest some approach how to do that?

**Comment by jonaswinkler** [comment]
You can use [supervisord](http://supervisord.org/).

* Install supervisord as part of the Dockerfile build.
* Make a supervisord configuration file that defines the services you want to start (probably some webserver and qcluster)
* Start supervisord instead of the webserver when the image starts.

I've done exactly that on a project myself and it's working out great for *many* users without a hitch. If you need some guidance, look at [Dockerfile](https://github.com/jonaswinkler/paperless-ng/blob/master/Dockerfile) (especially the CMD line further down), [supervisord.conf](https://github.com/jonaswinkler/paperless-ng/blob/master/docker/supervisord.conf) and [one of the compose files](https://github.com/jonaswinkler/paperless-ng/blob/master/docker/compose/docker-compose.sqlite.yml) of that project.

**Comment by mhassan91** [comment]
You need to run 2 docker containers. One for application server and one for django-q service. Your dockercompose file will look like this.

version: "3.9"
   
services:  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  django-q:
    build: .
    command: python manage.py django-q
    volumes:
      - .:/code
    depends_on:
      - redis

**Comment by Koed00** [comment]
There is a very small section on deploying with supervisor or circus in the docs: https://django-q.readthedocs.io/en/latest/cluster.html?highlight=heroku#process-managers
Maybe time to expand that section.

**Comment by Ondrados** [comment]
@jonaswinkler @mhassan91 @Koed00 Thank you for your answers. I will end up with solution that mentions @mhassan91 which is exactly what i meant by building same image with different command. Supervisor or Circus approach is for me little bit complicated.

**Comment by jonaswinkler** [comment]
Just be aware that this will complicate the setup for users that don't have access to docker-compose.

**Comment by rclement** [comment]
Another way: using Heroku's `Procfile` file format combined with [`honcho`](https://github.com/nickstenning/honcho).

Example of `Procfile`:

```
web: gunicorn app.wsgi:application
worker: python manage.py qcluster
```

Within the `Dockerfile`:

```dockerfile
ENTRYPOINT ["honcho", "start"]
CMD ["web", "worker"]
```

By default the container will start both processes within it, but you can override the `CMD` withint a `docker-compose.yml` configuration:

```yaml
version: "3.9"
   
services:  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  web:
    build: .
    command: ["web"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  django-q:
    build: .
    command: ["worker"]
    volumes:
      - .:/code
    depends_on:
      - redis
```
