### ISSUE TITLE
How to deploy Django and django-q with Django ORM broker in a docker-compose.yml

### ISSUE THREAD

**Issue by Nicksia** [Koed00/django-q#622]
Hello all,

I already built an image which includes Django framework, djano-q and other function needed packages.

For me now, If I only run Django web service and then go inside the container to run the command: `python manage.py qcluster`, Scheduler and async tasks could be work normally.

However, I should have one process per container right ? Docker official document also said that it is generally recommended that you separate areas of concern by using one service per container. 

I had read the issue #513, The results I found on google are all applied redis as the broker. Because my project has already deployed many services, I wish to apply Django ORM as the broker.

settings.py
```
Q_CLUSTER = {
    'name': 'pdm',
    'workers': 1,
    'recycle': 500,
    'timeout': 60,
    'retry': 120,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'daemonize_workers': False,
    'orm': 'default',
}
```

docker-compose.yml
```
version: "3"
services:  
  web:
    image: mydjango:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  django-q:
    image: mydjango:latest
    command: python manage.py qcluster
```

I don't know how to let Django web service communicate with django-q. 

The correct work flow and relationship I thought is like the following:
step1: Once the task is created in Django web service, it will send to web's broker (Django ORM)
step2: At the same time, django-q will start to run the task process. logs are logged in this container.
step3: Finally, results are send to web service's broker. All results also can be watched in Django admin. 

Is the above description correct ?

Reference:
- https://forum.djangoproject.com/t/django-and-django-q-in-one-container/7403
- https://github.com/Koed00/django-q/issues/513
 .

**Comment by nickodell** [comment]
The ORM broker is the slowest broker (in that it needs to repeatedly poll the database to find new work) and the least robust (in that exactly-once delivery is not what the Django ORM is intended to provide, and hacks are required to accomplish it.)

I would strongly suggest you not try to use the ORM broker. If you're already using Docker Compose anyway, then running an additional redis service doesn't have any new operational cost. I'd suggest changing your compose file like this:

```
version: "3"
services:  
  web:
    image: mydjango:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  django-q:
    image: mydjango:latest
    command: python manage.py qcluster
    depends_on:
      - "jobqueue"
  # Redis server for storing async tasks in progress
  jobqueue:
    image: bitnami/redis
    ports:
      - '127.0.0.1:6379:6379'
```

---

However, if you insist on using the ORM broker, then you can accomplish it by making sure that the qcluster container has access to the database. The ORM broker doesn't communicate directly to the Django process. Rather, it communicates to the database, as does Django. In other words, if Django Q can access the database, then you don't need to do anything else.
